on:
  # Triggers the workflow
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  run_checks:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.3"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff
        run: uv run ruff check src/mark_filter

      - name: Run tests
        run: uv run pytest testing
